version: '3.8'

services:

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    depends_on:
      - mariadb
    volumes:
      - ./logs:/home/logs
    ports:
      - 14565:14565

  mariadb:
    image: mariadb:latest
    command: --max_allowed_packet=32505856
    volumes:
      - ./mariadb:/var/lib/mysql
    expose:
      - 3306
    env_file:
      - ./mariadb_env.txt

  pma:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 3307:80
    environment:
      - PMA_HOST=mariadb
