name: CI
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: deploy
        run: |
          sudo apt update
          sudo apt install openssh-client
          mkdir -p ~/.ssh
          eval $(ssh-agent -s)
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")
          ssh -o StrictHostKeyChecking=no root@89.116.44.182 -p 5829 './strawberry_backup.sh'
