name: CI
on: [push]
jobs:
  Build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: deploy
        run: |
          sudo apt update
          sudo apt install openssh-client
          sudo mkdir -p ~/.ssh
          sudo eval $(ssh-agent -s)
          sudo echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          sudo ssh-add <(echo "$SSH_PRIVATE_KEY")
          sudo ssh -o StrictHostKeyChecking=no root@66.150.64.139 -p 5829 './strawberry_bachup.sh'
